Add Pipfile
nrkno/akamai-datastream-influxdb pull request #4
Opened 2020-02-18 10:11 UTC by joberget

2020-02-18 10:38 UTC, umglurf approved these changes

2020-02-18 10:38 UTC, umglurf requested changes
Dette holder vel ikke, den må brukes i bygget også

2020-02-18 12:21 UTC, umglurf submitted a review, later dismissed
regner med du har testet at det virker :)

2020-02-18 12:27 UTC, joberget commented
Har ikke testet ting enn, men its coming!

2020-03-02 14:51 UTC, joberget commented
Tar du en til sjekk?

2020-03-02 14:56 UTC, umglurf requested changes

2020-03-02 14:56 UTC, umglurf commented on Dockerfile
> +    find /var/lib/apt/lists -type f -delete
move up to base

2020-03-02 15:00 UTC, umglurf approved these changes
LGTM

2020-03-03 08:22 UTC, merged